"""Where the false-positive budget is spent.

Every detector in this scanner has a legitimate construct that trips it.
Minified bundles are high-entropy and call ``Function``. Generated protobuf code
has unnatural identifier distributions. Lockfiles are walls of hashes. None of
these are anomalies; they are just what those files look like.

The distinction this module draws is not "suspicious versus safe" but *"did a
human write this"*. Machine-generated and vendored files are held to a different
standard because a human reviewer was never going to read them anyway -- their
provenance, not their contents, is what should be checked.

Shape-based detection matters as much as name-based: an attacker who ships a
payload can call the file ``app.js`` instead of ``app.min.js``, but cannot make
a 20 KB single line look hand-written.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import pathspec

from ..models import Finding

HEADER_SCAN_LINES = 5
"""Generated-file markers are conventionally in the first few lines. Scanning
the whole file would match the phrase wherever it appears in ordinary prose."""

MINIFIED_MEAN_LINE_LENGTH = 200
MINIFIED_MAX_LINE_LENGTH = 2000
MINIFIED_MIN_BYTES = 1024


class SuppressionReason(str, Enum):
    VENDORED = "vendored"
    LOCKFILE = "lockfile"
    MINIFIED = "minified"
    GENERATED = "generated"
    CONFIGURED = "configured"


VENDORED_DIRECTORIES = frozenset(
    {
        "node_modules",
        "vendor",
        "third_party",
        "thirdparty",
        "bower_components",
        "site-packages",
        "dist-packages",
        "eggs",
        ".yarn",
        "Godeps",
        "_vendor",
    }
)

LOCKFILE_NAMES = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "npm-shrinkwrap.json",
        "poetry.lock",
        "pdm.lock",
        "uv.lock",
        "Pipfile.lock",
        "requirements.txt",
        "Cargo.lock",
        "go.sum",
        "composer.lock",
        "Gemfile.lock",
    }
)

_BUNDLE_NAME_RE = re.compile(
    r"\.(min|bundle|chunk|packed)\.(js|css|mjs|cjs)$|\.min$|-min\.(js|css)$|\.js\.map$",
    re.IGNORECASE,
)

_GENERATED_MARKER_RE = re.compile(
    r"""(
        @generated
      | DO\s+NOT\s+EDIT
      | Code\s+generated\s+by
      | Generated\s+by\s+\S
      | This\s+file\s+(is|was)\s+(auto[- ]?)?generated
      | Autogenerated
      | machine[- ]generated
    )""",
    re.VERBOSE | re.IGNORECASE,
)


@dataclass
class Suppressor:
    """Decides which files are held to a lower standard, and says why."""

    root: Path
    enabled: bool = True
    extra_paths: list[str] = field(default_factory=list)
    _spec: pathspec.PathSpec[pathspec.Pattern] | None = None

    def __post_init__(self) -> None:
        self._spec = pathspec.PathSpec.from_lines("gitignore", self.extra_paths)

    def reason_for(self, path: Path, content: bytes | None = None) -> SuppressionReason | None:
        """Why this file should be suppressed, or ``None`` to judge it normally."""
        if not self.enabled:
            return None

        if self._spec is not None and self._spec.match_file(self._relative(path)):
            return SuppressionReason.CONFIGURED
        if VENDORED_DIRECTORIES & set(path.parts):
            return SuppressionReason.VENDORED
        if path.name in LOCKFILE_NAMES:
            return SuppressionReason.LOCKFILE
        if _BUNDLE_NAME_RE.search(path.name):
            return SuppressionReason.MINIFIED
        if content:
            if self._has_generated_marker(content):
                return SuppressionReason.GENERATED
            if self._looks_minified(content):
                return SuppressionReason.MINIFIED
        return None

    def partition(
        self, findings: list[Finding], contents: dict[Path, bytes]
    ) -> tuple[list[Finding], list[Finding]]:
        """Split findings into those to report and those to hold back."""
        reported: list[Finding] = []
        suppressed: list[Finding] = []
        cache: dict[Path, SuppressionReason | None] = {}

        for finding in findings:
            path = finding.location.path
            if path not in cache:
                cache[path] = self.reason_for(path, contents.get(path))
            reason = cache[path]
            if reason is None:
                reported.append(finding)
            else:
                finding.metadata["suppressed_by"] = reason.value
                suppressed.append(finding)
        return reported, suppressed

    # -- shape heuristics --------------------------------------------------

    @staticmethod
    def _has_generated_marker(content: bytes) -> bool:
        head = content[:4096].decode("utf-8", errors="replace").splitlines()[:HEADER_SCAN_LINES]
        return any(_GENERATED_MARKER_RE.search(line) for line in head)

    @staticmethod
    def _looks_minified(content: bytes) -> bool:
        """Line geometry, which survives renaming the file.

        Minifiers strip newlines, so the mean line length explodes while the
        line count collapses. Ordinary code with long lines fails the mean test
        even when individual lines are long.
        """
        if len(content) < MINIFIED_MIN_BYTES:
            return False
        lines = content.split(b"\n")
        non_empty = [line for line in lines if line.strip()]
        if not non_empty:
            return False
        mean = sum(len(line) for line in non_empty) / len(non_empty)
        longest = max(len(line) for line in non_empty)
        return mean > MINIFIED_MEAN_LINE_LENGTH or longest > MINIFIED_MAX_LINE_LENGTH

    def _relative(self, path: Path) -> str:
        try:
            return path.relative_to(self.root).as_posix()
        except ValueError:
            return path.as_posix()
