"""Tests for suppression, baselining and risk scoring.

Together these are the false-positive budget. A scanner that reports every true
anomaly and nothing else would still be uninstalled on day one if the true
anomalies in a healthy repo number in the hundreds.
"""

import json
from pathlib import Path

import pytest

from forensic_scan.models import Finding, Location, Severity
from forensic_scan.scoring.baseline import Baseline
from forensic_scan.scoring.score import RiskScore, exit_code_for, score_findings
from forensic_scan.scoring.suppress import SuppressionReason, Suppressor

ROOT = Path("/repo")


def _finding(rule_id="FOR-001", path="a.py", line=1, severity=Severity.HIGH, snippet="eval(x)"):
    return Finding(
        rule_id=rule_id,
        name="Test finding",
        severity=severity,
        location=Location(path=ROOT / path, line=line, snippet=snippet),
        detail="detail",
        remediation="fix",
    )


class TestSuppressor:
    @pytest.fixture
    def suppressor(self):
        return Suppressor(root=ROOT)

    def test_a_plain_source_file_is_not_suppressed(self, suppressor):
        assert suppressor.reason_for(ROOT / "src/app.py", b"x = 1\n") is None

    @pytest.mark.parametrize(
        "path",
        [
            "node_modules/pkg/index.js",
            "vendor/lib/thing.go",
            "third_party/x/y.c",
            "src/vendor/dep.js",
        ],
    )
    def test_vendored_paths_are_suppressed(self, suppressor, path):
        assert suppressor.reason_for(ROOT / path, b"x") is SuppressionReason.VENDORED

    @pytest.mark.parametrize(
        "name",
        ["package-lock.json", "yarn.lock", "poetry.lock", "Cargo.lock", "pnpm-lock.yaml"],
    )
    def test_lockfiles_are_suppressed(self, suppressor, name):
        assert suppressor.reason_for(ROOT / name, b"{}") is SuppressionReason.LOCKFILE

    @pytest.mark.parametrize("name", ["app.min.js", "bundle.min.css", "x.bundle.js"])
    def test_files_named_as_bundles_are_suppressed(self, suppressor, name):
        assert suppressor.reason_for(ROOT / name, b"x") is SuppressionReason.MINIFIED

    def test_a_minified_file_is_detected_by_shape_not_only_by_name(self, suppressor):
        """An attacker renames the file; the line geometry still gives it away."""
        content = (b"function a(b,c){return b+c}" * 400) + b"\n"
        assert suppressor.reason_for(ROOT / "app.js", content) is SuppressionReason.MINIFIED

    def test_normal_code_with_long_lines_is_not_called_minified(self, suppressor):
        content = b"\n".join(
            b"    const someReasonablyLongVariableName = computeSomething(a, b, c);"
            for _ in range(200)
        )
        assert suppressor.reason_for(ROOT / "app.js", content) is None

    @pytest.mark.parametrize(
        "marker",
        [
            b"// Code generated by protoc-gen-go. DO NOT EDIT.\n",
            b"# @generated by the build system\n",
            b"/* eslint-disable */\n// @generated\n",
            b"# Generated by Django 4.2 on 2024-01-01\n",
        ],
    )
    def test_generated_file_markers_are_honoured(self, suppressor, marker):
        content = marker + b"x = 1\n" * 50
        assert suppressor.reason_for(ROOT / "gen.py", content) is SuppressionReason.GENERATED

    def test_a_generated_marker_deep_in_a_file_is_ignored(self, suppressor):
        """Only a header counts; the phrase appears in ordinary prose and comments."""
        content = b"x = 1\n" * 200 + b"# this file is not @generated by anything\n"
        assert suppressor.reason_for(ROOT / "app.py", content) is None

    def test_suppression_can_be_disabled_entirely(self):
        suppressor = Suppressor(root=ROOT, enabled=False)
        assert suppressor.reason_for(ROOT / "node_modules/x.js", b"x") is None

    def test_extra_paths_can_be_suppressed_by_configuration(self):
        suppressor = Suppressor(root=ROOT, extra_paths=["generated/**"])
        assert (
            suppressor.reason_for(ROOT / "generated/api.py", b"x") is SuppressionReason.CONFIGURED
        )

    def test_partitions_findings_into_reported_and_suppressed(self, suppressor):
        findings = [_finding(path="src/a.py"), _finding(path="node_modules/b.js")]
        reported, suppressed = suppressor.partition(findings, {})
        assert [f.location.path.name for f in reported] == ["a.py"]
        assert [f.location.path.name for f in suppressed] == ["b.js"]

    def test_a_suppressed_finding_records_why(self, suppressor):
        _, suppressed = suppressor.partition([_finding(path="vendor/x.js")], {})
        assert suppressed[0].metadata["suppressed_by"] == "vendored"


class TestBaseline:
    def test_an_absent_baseline_file_suppresses_nothing(self, tmp_path):
        baseline = Baseline.load(tmp_path / "nope.json")
        assert baseline.is_empty
        assert not baseline.contains(_finding())

    def test_a_recorded_finding_is_recognised(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding()]).save(path, root=ROOT)
        assert Baseline.load(path).contains(_finding())

    def test_an_unrecorded_finding_is_not_recognised(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding(rule_id="FOR-001")]).save(path, root=ROOT)
        assert not Baseline.load(path).contains(_finding(rule_id="FOR-002"))

    def test_a_baselined_finding_survives_unrelated_edits_above_it(self, tmp_path):
        """Adding an import at the top of a file must not un-accept a finding."""
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding(line=10)]).save(path, root=ROOT)
        assert Baseline.load(path).contains(_finding(line=42))

    def test_changing_the_flagged_code_does_un_accept_it(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding(snippet="eval(x)")]).save(path, root=ROOT)
        assert not Baseline.load(path).contains(_finding(snippet="eval(untrusted_input)"))

    def test_the_file_is_human_readable_and_explains_itself(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding()]).save(path, root=ROOT)
        data = json.loads(path.read_text())
        assert data["version"] == 1
        entry = next(iter(data["findings"].values()))
        assert entry["rule"] == "FOR-001"
        assert entry["path"] == "a.py"
        assert "note" in data

    def test_paths_are_stored_relative_to_the_repository(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding(path="src/deep/a.py")]).save(path, root=ROOT)
        entry = next(iter(json.loads(path.read_text())["findings"].values()))
        assert entry["path"] == "src/deep/a.py"

    def test_a_corrupt_baseline_raises_a_clear_error(self, tmp_path):
        path = tmp_path / "baseline.json"
        path.write_text("{not json")
        with pytest.raises(ValueError, match="baseline"):
            Baseline.load(path)

    def test_filtering_returns_only_new_findings(self, tmp_path):
        path = tmp_path / "baseline.json"
        Baseline.from_findings([_finding(rule_id="FOR-001")]).save(path, root=ROOT)
        baseline = Baseline.load(path)
        new, accepted = baseline.partition(
            [_finding(rule_id="FOR-001"), _finding(rule_id="FOR-002")]
        )
        assert [f.rule_id for f in new] == ["FOR-002"]
        assert [f.rule_id for f in accepted] == ["FOR-001"]


class TestRiskScore:
    def test_no_findings_scores_zero(self):
        score = score_findings([])
        assert score.value == 0
        assert score.band == "CLEAN"

    def test_the_band_reflects_the_most_severe_finding(self):
        score = score_findings(
            [_finding(severity=Severity.CRITICAL), _finding(severity=Severity.LOW)]
        )
        assert score.band == "CRITICAL"

    def test_a_critical_finding_scores_high(self):
        assert score_findings([_finding(severity=Severity.CRITICAL)]).value >= 70

    def test_a_single_low_finding_scores_low(self):
        assert score_findings([_finding(severity=Severity.LOW)]).value <= 10

    def test_severity_dominates_volume(self):
        """Fifty style nits must not outrank one smuggled executable."""
        many_low = score_findings([_finding(severity=Severity.LOW) for _ in range(50)])
        one_critical = score_findings([_finding(severity=Severity.CRITICAL)])
        assert one_critical.band == "CRITICAL"
        assert many_low.band == "LOW"

    def test_the_score_saturates_rather_than_overflowing(self):
        score = score_findings([_finding(severity=Severity.CRITICAL) for _ in range(500)])
        assert score.value <= 100

    def test_the_score_is_monotonic_in_findings(self):
        one = score_findings([_finding(severity=Severity.HIGH)])
        two = score_findings([_finding(severity=Severity.HIGH), _finding(severity=Severity.HIGH)])
        assert two.value > one.value

    def test_counts_are_reported_per_severity(self):
        score = score_findings(
            [
                _finding(severity=Severity.CRITICAL),
                _finding(severity=Severity.HIGH),
                _finding(severity=Severity.HIGH),
            ]
        )
        assert score.counts[Severity.HIGH] == 2
        assert score.counts[Severity.CRITICAL] == 1

    def test_low_confidence_findings_contribute_less(self):
        confident = _finding(severity=Severity.HIGH)
        unsure = _finding(severity=Severity.HIGH)
        unsure.metadata["confidence"] = 0.3
        assert score_findings([confident]).value > score_findings([unsure]).value


class TestExitCodes:
    def test_clean_scan_exits_zero(self):
        assert exit_code_for([], fail_on=Severity.MEDIUM) == 0

    def test_a_finding_at_the_threshold_exits_one(self):
        assert exit_code_for([_finding(severity=Severity.MEDIUM)], fail_on=Severity.MEDIUM) == 1

    def test_a_finding_above_the_threshold_exits_one(self):
        assert exit_code_for([_finding(severity=Severity.CRITICAL)], fail_on=Severity.MEDIUM) == 1

    def test_a_finding_below_the_threshold_exits_zero(self):
        assert exit_code_for([_finding(severity=Severity.LOW)], fail_on=Severity.MEDIUM) == 0

    def test_a_threshold_of_none_never_fails(self):
        assert exit_code_for([_finding(severity=Severity.CRITICAL)], fail_on=None) == 0


class TestRiskScoreRendering:
    def test_renders_as_band_and_value(self):
        score = RiskScore(value=88, band="CRITICAL", counts={Severity.CRITICAL: 1})
        assert str(score) == "CRITICAL (88/100)"
